### ISSUE TITLE
storage location

### ISSUE THREAD

**Issue by umardraz** [CenterForOpenScience/waterbutler#166]
Hi,

What is the storage location for upload files?

**Comment by felliott** [comment]
For `osfstorage`, correct?  The default for that is the `/website/osfstoragecache/` directory in your OSF repo.  You can change that here: https://github.com/CenterForOpenScience/osf.io/blob/847824cf86ddd7403a9b18b1ff3278cd8399ab63/website/addons/osfstorage/settings/defaults.py#L15
