### ISSUE TITLE
Problems with https

### ISSUE THREAD

**Issue by sonnenschein123** [CenterForOpenScience/waterbutler#173]
I have tried to make waterbutler reachable via https, but if I try to connect osf with the waterbutler all I get is the message "waterbutler.core.exceptions.AuthError: 503, Unable to connect to auth sever". Has anyone an Idea what I can do?

**Comment by felliott** [comment]
Hey @sonnenschein123!

Can you paste the console output from the OSF and WB into a gist and link it here?  You might also check to make sure that the salts and secrets config values in https://github.com/CenterForOpenScience/waterbutler/blob/develop/waterbutler/auth/osf/settings.py match up with the corresponding settings in the OSF.

Cheers,
@felliott

**Comment by sonnenschein123** [comment]
Hey @felliott,
thanks for your answer. 
Here is the WB output [https://gist.github.com/sonnenschein123/67a52e3ddcd06a971ed1b5e49fdc1f08](url). OSF has no output. JWE_SALT, JWE_SECRET and JWT_SECRET is the same as in OSF. 

Best,
@sonnenschein123

**Comment by felliott** [comment]
Hrm, that's a strange one.  WB is trying to connect to your local OSF over https, but unable to.  How are adding SSL support to the OSF?  Are you running a proxy in front of it?  Also, I noticed in [this line](https://gist.github.com/sonnenschein123/67a52e3ddcd06a971ed1b5e49fdc1f08#file-gistfile1-txt-L19) that you seem to try to be connecting to `127.0.*1*.1`.  Is that a typo?  `127.0.*0*.1` is usually used for localhost.

**Comment by sonnenschein123** [comment]
Hey, 
I edit the local hosts file, so that the server use the IP address to connect to them self instead of 127.0.1.1. Thank you for pointing that out. Now I get this error message https://gist.github.com/sonnenschein123/e00786408bf212cbf8b43fb13670652b

**Comment by felliott** [comment]
Can you connect to the https OSF with a browser?  What is the output of this command? `curl -I -XGET https://osf.coll.mpg.de:5000/`

**Comment by sonnenschein123** [comment]
I can connect to OSF via https with the browser. When I run the `curl -I -XGET https://osf.coll.mpg.de:5000/` I get the message "curl: (60) SSL certificate problem: unable to get local issuer certificate"

**Comment by felliott** [comment]
Are you using a self-signed certificate?

**Comment by sonnenschein123** [comment]
No, it is an official-signed certificate.

**Comment by felliott** [comment]
If curl can't connect to it, WB probably won't be able to either.  Maybe your system certificates are out-of-date?  What platform are you running on?

**Comment by sonnenschein123** [comment]
I'm run on an Ubuntu 14.04. 
Firefox says that the certificate is fine.
![osf coll mpg de_cert](https://cloud.githubusercontent.com/assets/19288720/19550597/7d7ea10c-96aa-11e6-9d2b-694e4443cdd1.png)

**Comment by felliott** [comment]
I think Firefox (and other browsers) tend to ship with and update their own certificate bundles, but the system certs are probably not up-to-date.  See [this question](http://askubuntu.com/questions/702882/curl-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate) on askubuntu.com.  If you have admin rights on this machine, check aptitude and see if you can upgrade the `ca-certificates` package.

**Comment by sonnenschein123** [comment]
Hey, I have solved this problem. The problem was that the issuer of the certificate was not known. So I put the public key of the issuer in my certificate and now it works. 
Thanks a lot for your support.
