### ISSUE TITLE
Store access rights with each file/folder instead of only at project level

### ISSUE THREAD

**Issue by dschreij** [CenterForOpenScience/waterbutler#197]
Currently, the access permissions are only listed at the project level. This makes it difficult to determine the access rights of individual files and folders inside a project. To do so, you need to check the parents of each file/folder, until you get to the project node that contains this information. Would it be possible to add this permission information to each child node of a project?

**Comment by dschreij** [comment]
See https://github.com/CenterForOpenScience/waterbutler/issues/188#issuecomment-283768652, for the discussion leading to creating this issue.

**Comment by felliott** [comment]
Hey @dschreij,

Sorry, I overlooked this one.  Do you mind closing and refiling this against the [osf.io](https://github.com/CenterForOpenScience/osf.io) repository?  The API folks who would need to implement this watch that repo.  Thank you!

Cheers,
@felliott

**Comment by dschreij** [comment]
Sure!
