### ISSUE TITLE
[staging & production] Better error message for out of space on Dropbox

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/waterbutler#33]
# Steps
1. Go to staging or production
2. Go to a project where you have admin access
3. Enable Dropbox 
4. Link and configure a Dropbox account that is out of space
5. Go to the files tab
6. Try to upload a file

# Expected
I expect that the file would not upload since the Dropbox account is out of space, *but* I expect an error message to identify this. 

# Actual
Dropbox sends back a 507 Internal Server Error and a very non-specific error is given to the user. 
![screen shot 2015-04-14 at 11 01 37 am](https://cloud.githubusercontent.com/assets/5975444/7139886/9287a98c-e296-11e4-8f56-861a515b1827.png)

I had no idea why I couldn't upload any files to Dropbox until @chrisseto looked at the trace and told me why uploads weren't working.
![screen shot 2015-04-14 at 10 00 29 am](https://cloud.githubusercontent.com/assets/5975444/7139917/bbd12516-e296-11e4-9139-8fc55802091c.png)

It would be helpful to identify why the user cannot upload a file. Dropbox gives the following message:
![screen shot 2015-04-14 at 11 10 54 am](https://cloud.githubusercontent.com/assets/5975444/7139964/f841b556-e296-11e4-98a2-e2456b19c078.png)

**Comment by TomBaxter** [comment]
I have created an osf.io pull request #4635 that should address this issue.

**Comment by TomBaxter** [comment]
@caileyfitz  The logic was updated in a different PR and I believe this issue can be closed.
@felliott Adding you because I'm not sure @caileyfitz is still active. I don't see any recent commits from her.

**Comment by caileyfitz** [comment]
Thanks @TomBaxter. I'll close this issue.
