### ISSUE TITLE
[Feature] Web hooks for remote storage changes

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/waterbutler#36]
A potentially nice feature would be to allow client services, such as the OSF, a simplified way to connect to third-party webhooks to indicate that files/folders have been updated. How useful this would be would depend on how common it is for file storage services to implement webhooks, but it looks like at least Dropbox, Box.com, and Google Drive support them. This would let services that use Waterbutler to match state much more easily that polling, especially if there's a way to standardize the webhook interface.

**Comment by felliott** [comment]
New Year's issue cleanup drive-by: this is better done on the OSF, since WB isn't really concerned with tracking state.  As an example, see the [GitHub addon](https://github.com/CenterForOpenScience/osf.io/blob/develop/addons/github/views.py#L263).  Closing.
