### ISSUE TITLE
[feature] Give hash when listing files metadata 

### ISSUE THREAD

**Issue by himanshuo** [CenterForOpenScience/waterbutler#51]
When listing file metadata, I think it would be a nice feature to also give a hash of the file. This is especially useful for the API since it uses the metadata that waterbutler provides it.

<b>Benefits</b>

<ol>
  <li>API User can verify that a file is not being downloaded from a malicious source (if user is downloading same file from some external, faster mirror)</li>
 <li>API User can verify that a file is not being corrupted in transit</li>
<li>API User can use this to quickly determine if their version of a file is the most recent version of the file (without having to mess around with date_modified)</li>
</ol>

http://superuser.com/a/201753

**Comment by chrisseto** [comment]
File hashes will be sent back with metadata when they are available from the source provider.
Its not feasible for waterbutler to compute hashes for files in various metadata listings as that would require downloading the each file that metadata is being requested about.

**Comment by hmoco** [comment]
However they will be available for OSFstorage once my pr is merged :smile: 
![screen shot 2015-07-15 at 10 57 29 am](https://cloud.githubusercontent.com/assets/6268982/8701544/61a7c74c-2ae0-11e5-9793-6a668b0660d5.png)

**Comment by felliott** [comment]
New Year's issue tidy-fest:  we do this for all providers as of v0.34.  See https://github.com/CenterForOpenScience/waterbutler/commit/ca21d8f143e822d39d5141e2c5a90f8f083a1369.  Marking as closed.
