### ISSUE TITLE
Deleted and copied files need to return paths

### ISSUE THREAD

**Issue by Ghalko** [CenterForOpenScience/waterbutler#53]
The subscriptions to files depends on waterbutler paths to some extent or another. Knowing the source of a copied file via the path or what file, or files were just deleted would allow the subscription to be appropriately notified.

To formalize the request:
- Callbacks should be given a list of effected waterbutler paths.
 - Copy should include list of source waterbutler paths
 - Deleted should replace the path which doubles the 'materialized' item for a list of waterbutler paths since it will be impossible to find the paths which were effected after the fact.
 - Possibly update all different file operations to return lists of effected items.

**Comment by Ghalko** [comment]
@icereval I am not familiar with the overall structure of WB, where would I change the path back to giving waterbutlerpaths on move and copy files?

**Comment by felliott** [comment]
Hey @Ghalko,

There were a bunch of fixes in the last few months to make sure callback payloads were returning correct and useful data to support addon comment updates.  See:

715af8aebc7f71ba3607360ddb1f5abb57ea6c9b
96480e952a3ec7f40659fdafb01e3d1a8f10a083
22d4a91268d99e29fcf32ec656791d4b4f18dcd5
79ddff0eb22911972f883176ff89cd7ebf37aed3
ce80e7daa0ac27f057b09dce03e8df65ece1a0d5
1830d01e607b62c8175b216e805c9131fec1e73c
4cdefa97dd0c3d00dfd10adb29a3f14147d9098b

Are there outstanding issues that aren't addressed by these?

Cheers,
@felliott

**Comment by Ghalko** [comment]
It has been so long that I can't be 100% positive on all of these, but it seems the requests have been met.
