### ISSUE TITLE
Modified and content type fields not showing up

### ISSUE THREAD

**Issue by himanshuo** [CenterForOpenScience/waterbutler#69]
In the below screen shot, I am accessing metadata information the api which is accessing waterbutler which is accessing osfstorage. The modified and content type fields are null. They should not be null.

Both these fields do in fact already exist in the osfstorage. I *think* the issue might be some issue in processing data coming from osfstorage to waterbutler.

![screen shot 2015-08-13 at 1 10 52 pm](https://cloud.githubusercontent.com/assets/5808841/9256306/ce053db4-41bc-11e5-9624-4fc3cd2e01b1.png)

![screen shot 2015-08-13 at 1 49 16 pm](https://cloud.githubusercontent.com/assets/5808841/9257169/22f6cb1c-41c2-11e5-8357-2bd301c1a990.png)

**Comment by himanshuo** [comment]
@brianjgeiger

**Comment by brianjgeiger** [comment]
@chrisseto Any thoughts on this? This is considered a Serious Problem.

**Comment by lbanner** [comment]
I can't label these, but if I could, I am sensing "Priority = High" @chrisseto @icereval

**Comment by chrisseto** [comment]
@lbanner Checking now
Note content type may not be available.

**Comment by chrisseto** [comment]
Fixed via https://github.com/CenterForOpenScience/osf.io/pull/4063 and https://github.com/CenterForOpenScience/waterbutler/commit/c44ca9ff45cd0a581e3505b2537e2245408a066a
